Assumption: Y-> linerly dependent to X(i)

"SKLEARN" - "NUMPY"

In [189]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [190]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [191]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [192]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [193]:
model = LinearRegression()

In [196]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [197]:
y_new = model.predict(x)

In [198]:
model.coef_, model.intercept_

(array([0.44706965, 0.25502548]), 5.5225792751981935)

In [199]:
cost_cal(y_new, y)

12.780935907417893

In [21]:
r_sq = model.score(x, y)

In [22]:
r_sq

0.8615939258756776

In [23]:
y_pred = model.predict(x)

In [24]:
y_pred

array([ 5.77760476,  8.012953  , 12.73867497, 17.9744479 , 23.97529728,
       29.4660957 , 38.78227633, 41.27265006])

In [25]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

"SELF"

In [26]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [27]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

Steps:
1. Matrix evaluation
2. Cost function
3. Gradient descent

Matrix evaluation

Output = Input * Weights

In [48]:
l = []
for i,e in enumerate(x):
    l.append(np.insert(e, 0, 1))
   

In [51]:
x_aug = np.array(l)

In [54]:
x_aug

array([[ 1,  0,  1],
       [ 1,  5,  1],
       [ 1, 15,  2],
       [ 1, 25,  5],
       [ 1, 35, 11],
       [ 1, 45, 15],
       [ 1, 55, 34],
       [ 1, 60, 35]])

In [57]:
x_aug.shape

(8, 3)

In [61]:
beta = np.random.rand(3,1)

In [63]:
beta.shape

(3, 1)

In [64]:
np.matmul(x_aug,beta)

array([[ 1.19110121],
       [ 2.35973099],
       [ 5.23363395],
       [ 9.18082372],
       [14.73794369],
       [19.22177686],
       [31.75526107],
       [33.46053425]])

In [163]:
def mat_evaluation(inp,weights):
    ans = np.matmul(inp, weights)
    return ans

In [80]:
mat_eva = mat_evaluation(x_aug,beta)

array([1.19110121])

Cost

In [69]:
m = len(y)

In [78]:
s = 0
for i in range(m):
    s = s + ((eva[i] - y[i])**2)
ans = s/(2*m)

In [79]:
ans

array([43.23914013])

In [173]:
def cost_cal(mat_eva, y):
    m = len(y)
    s = 0
    for i in range(m):
        s = s + ((mat_eva[i] - y[i])**2)
    ans = s/(2*m)
    return (ans)

In [83]:
c = cost_cal(mat_eva, y)

In [84]:
c

array([43.23914013])

Gradient Descent

In [104]:
alpha = 0.001

In [91]:
j = 1

In [97]:
m = len(y)

In [105]:
s = 0
for i in range(m):
    s = s + (((mat_eva[i] - y[i]))*x_aug[i][j])
ans = alpha*(1/m)*(s)
    

In [106]:
def gradient_descent_bj(mat_eva, y, x_aug, j):
    alpha = 0.001
    m = len(y)
    s = 0
    for i in range(m):
        s = s + (((mat_eva[i] - y[i]))*x_aug[i][j])
    ans = alpha*(1/m)*(s)
    return (ans)


In [109]:
gradient_descent_bj(mat_eva, y, x_aug, 1)

array([-0.25002461])

Implementation

In [110]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [112]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [111]:
x_aug

array([[ 1,  0,  1],
       [ 1,  5,  1],
       [ 1, 15,  2],
       [ 1, 25,  5],
       [ 1, 35, 11],
       [ 1, 45, 15],
       [ 1, 55, 34],
       [ 1, 60, 35]])

In [120]:
beta = np.random.rand(3,1)
beta

array([[0.71919416],
       [0.15833675],
       [0.43642048]])

In [181]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [182]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

/Users/Rohan/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/Rohan/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [183]:
x

array([[-1.42413799, -0.90517714],
       [-1.18678166, -0.90517714],
       [-0.71206899, -0.82974572],
       [-0.23735633, -0.60345143],
       [ 0.23735633, -0.15086286],
       [ 0.71206899,  0.15086286],
       [ 1.18678166,  1.58406   ],
       [ 1.42413799,  1.65949143]])

In [184]:
l = []
for i,e in enumerate(x):
    l.append(np.insert(e, 0, 1))
x_aug = np.array(l)
    
epoch = 3000
beta = np.random.rand(len(x[0])+1,1)

for ep in range(epoch):
    print("Epoch:", ep)
#     print("Beta:", beta)
    y_hat = mat_evaluation(x_aug, beta)
#     print("mat_eva:", y_hat)
    c = cost_cal(y_hat, y)
    print("Cost:", c)

    for j, b in enumerate(beta):
        beta[j]= beta[j] - gradient_descent_bj(y_hat, y, x_aug, j)

Epoch: 0
Cost: [320.44202721]
Epoch: 1
Cost: [319.70276944]
Epoch: 2
Cost: [318.96547356]
Epoch: 3
Cost: [318.23013379]
Epoch: 4
Cost: [317.49674435]
Epoch: 5
Cost: [316.7652995]
Epoch: 6
Cost: [316.03579352]
Epoch: 7
Cost: [315.30822067]
Epoch: 8
Cost: [314.58257529]
Epoch: 9
Cost: [313.85885168]
Epoch: 10
Cost: [313.13704419]
Epoch: 11
Cost: [312.41714719]
Epoch: 12
Cost: [311.69915505]
Epoch: 13
Cost: [310.98306218]
Epoch: 14
Cost: [310.26886299]
Epoch: 15
Cost: [309.55655191]
Epoch: 16
Cost: [308.84612339]
Epoch: 17
Cost: [308.13757192]
Epoch: 18
Cost: [307.43089196]
Epoch: 19
Cost: [306.72607804]
Epoch: 20
Cost: [306.02312468]
Epoch: 21
Cost: [305.32202641]
Epoch: 22
Cost: [304.62277779]
Epoch: 23
Cost: [303.92537341]
Epoch: 24
Cost: [303.22980785]
Epoch: 25
Cost: [302.53607573]
Epoch: 26
Cost: [301.84417168]
Epoch: 27
Cost: [301.15409033]
Epoch: 28
Cost: [300.46582637]
Epoch: 29
Cost: [299.77937446]
Epoch: 30
Cost: [299.0947293]
Epoch: 31
Cost: [298.41188561]
Epoch: 32
Cost: [297

Cost: [160.92145177]
Epoch: 316
Cost: [160.58949161]
Epoch: 317
Cost: [160.25833854]
Epoch: 318
Cost: [159.9279904]
Epoch: 319
Cost: [159.59844502]
Epoch: 320
Cost: [159.26970026]
Epoch: 321
Cost: [158.94175396]
Epoch: 322
Cost: [158.61460399]
Epoch: 323
Cost: [158.28824821]
Epoch: 324
Cost: [157.96268449]
Epoch: 325
Cost: [157.6379107]
Epoch: 326
Cost: [157.31392475]
Epoch: 327
Cost: [156.99072451]
Epoch: 328
Cost: [156.66830788]
Epoch: 329
Cost: [156.34667276]
Epoch: 330
Cost: [156.02581707]
Epoch: 331
Cost: [155.70573872]
Epoch: 332
Cost: [155.38643564]
Epoch: 333
Cost: [155.06790574]
Epoch: 334
Cost: [154.75014697]
Epoch: 335
Cost: [154.43315727]
Epoch: 336
Cost: [154.11693458]
Epoch: 337
Cost: [153.80147685]
Epoch: 338
Cost: [153.48678205]
Epoch: 339
Cost: [153.17284813]
Epoch: 340
Cost: [152.85967308]
Epoch: 341
Cost: [152.54725486]
Epoch: 342
Cost: [152.23559146]
Epoch: 343
Cost: [151.92468086]
Epoch: 344
Cost: [151.61452107]
Epoch: 345
Cost: [151.30511008]
Epoch: 346
Cost: [150

Epoch: 801
Cost: [64.71596585]
Epoch: 802
Cost: [64.60782473]
Epoch: 803
Cost: [64.49992163]
Epoch: 804
Cost: [64.39225599]
Epoch: 805
Cost: [64.28482726]
Epoch: 806
Cost: [64.17763486]
Epoch: 807
Cost: [64.07067826]
Epoch: 808
Cost: [63.96395688]
Epoch: 809
Cost: [63.85747019]
Epoch: 810
Cost: [63.75121763]
Epoch: 811
Cost: [63.64519864]
Epoch: 812
Cost: [63.53941268]
Epoch: 813
Cost: [63.43385919]
Epoch: 814
Cost: [63.32853765]
Epoch: 815
Cost: [63.22344749]
Epoch: 816
Cost: [63.11858817]
Epoch: 817
Cost: [63.01395916]
Epoch: 818
Cost: [62.90955991]
Epoch: 819
Cost: [62.80538988]
Epoch: 820
Cost: [62.70144854]
Epoch: 821
Cost: [62.59773534]
Epoch: 822
Cost: [62.49424976]
Epoch: 823
Cost: [62.39099126]
Epoch: 824
Cost: [62.2879593]
Epoch: 825
Cost: [62.18515336]
Epoch: 826
Cost: [62.0825729]
Epoch: 827
Cost: [61.9802174]
Epoch: 828
Cost: [61.87808633]
Epoch: 829
Cost: [61.77617917]
Epoch: 830
Cost: [61.67449538]
Epoch: 831
Cost: [61.57303445]
Epoch: 832
Cost: [61.47179586]
Epoch: 833


Epoch: 1224
Cost: [34.72378475]
Epoch: 1225
Cost: [34.68012165]
Epoch: 1226
Cost: [34.63654996]
Epoch: 1227
Cost: [34.59306947]
Epoch: 1228
Cost: [34.54967998]
Epoch: 1229
Cost: [34.5063813]
Epoch: 1230
Cost: [34.46317323]
Epoch: 1231
Cost: [34.42005557]
Epoch: 1232
Cost: [34.37702813]
Epoch: 1233
Cost: [34.3340907]
Epoch: 1234
Cost: [34.2912431]
Epoch: 1235
Cost: [34.24848512]
Epoch: 1236
Cost: [34.20581658]
Epoch: 1237
Cost: [34.16323726]
Epoch: 1238
Cost: [34.120747]
Epoch: 1239
Cost: [34.07834558]
Epoch: 1240
Cost: [34.03603281]
Epoch: 1241
Cost: [33.99380851]
Epoch: 1242
Cost: [33.95167247]
Epoch: 1243
Cost: [33.90962452]
Epoch: 1244
Cost: [33.86766444]
Epoch: 1245
Cost: [33.82579207]
Epoch: 1246
Cost: [33.7840072]
Epoch: 1247
Cost: [33.74230964]
Epoch: 1248
Cost: [33.7006992]
Epoch: 1249
Cost: [33.6591757]
Epoch: 1250
Cost: [33.61773895]
Epoch: 1251
Cost: [33.57638875]
Epoch: 1252
Cost: [33.53512492]
Epoch: 1253
Cost: [33.49394727]
Epoch: 1254
Cost: [33.45285562]
Epoch: 1255
Cost

Cost: [24.59969575]
Epoch: 1541
Cost: [24.57700035]
Epoch: 1542
Cost: [24.5543514]
Epoch: 1543
Cost: [24.53174881]
Epoch: 1544
Cost: [24.50919249]
Epoch: 1545
Cost: [24.48668233]
Epoch: 1546
Cost: [24.46421825]
Epoch: 1547
Cost: [24.44180013]
Epoch: 1548
Cost: [24.41942789]
Epoch: 1549
Cost: [24.39710142]
Epoch: 1550
Cost: [24.37482064]
Epoch: 1551
Cost: [24.35258545]
Epoch: 1552
Cost: [24.33039574]
Epoch: 1553
Cost: [24.30825143]
Epoch: 1554
Cost: [24.28615242]
Epoch: 1555
Cost: [24.26409862]
Epoch: 1556
Cost: [24.24208992]
Epoch: 1557
Cost: [24.22012624]
Epoch: 1558
Cost: [24.19820747]
Epoch: 1559
Cost: [24.17633353]
Epoch: 1560
Cost: [24.15450433]
Epoch: 1561
Cost: [24.13271976]
Epoch: 1562
Cost: [24.11097973]
Epoch: 1563
Cost: [24.08928415]
Epoch: 1564
Cost: [24.06763293]
Epoch: 1565
Cost: [24.04602597]
Epoch: 1566
Cost: [24.02446319]
Epoch: 1567
Cost: [24.00294448]
Epoch: 1568
Cost: [23.98146975]
Epoch: 1569
Cost: [23.96003892]
Epoch: 1570
Cost: [23.93865189]
Epoch: 1571
Cost: [23

Epoch: 1989
Cost: [17.91264541]
Epoch: 1990
Cost: [17.90350959]
Epoch: 1991
Cost: [17.89439208]
Epoch: 1992
Cost: [17.88529284]
Epoch: 1993
Cost: [17.87621185]
Epoch: 1994
Cost: [17.86714905]
Epoch: 1995
Cost: [17.85810443]
Epoch: 1996
Cost: [17.84907793]
Epoch: 1997
Cost: [17.84006952]
Epoch: 1998
Cost: [17.83107917]
Epoch: 1999
Cost: [17.82210683]
Epoch: 2000
Cost: [17.81315248]
Epoch: 2001
Cost: [17.80421606]
Epoch: 2002
Cost: [17.79529756]
Epoch: 2003
Cost: [17.78639693]
Epoch: 2004
Cost: [17.77751412]
Epoch: 2005
Cost: [17.76864912]
Epoch: 2006
Cost: [17.75980188]
Epoch: 2007
Cost: [17.75097236]
Epoch: 2008
Cost: [17.74216053]
Epoch: 2009
Cost: [17.73336636]
Epoch: 2010
Cost: [17.7245898]
Epoch: 2011
Cost: [17.71583082]
Epoch: 2012
Cost: [17.70708938]
Epoch: 2013
Cost: [17.69836546]
Epoch: 2014
Cost: [17.689659]
Epoch: 2015
Cost: [17.68096998]
Epoch: 2016
Cost: [17.67229837]
Epoch: 2017
Cost: [17.66364412]
Epoch: 2018
Cost: [17.6550072]
Epoch: 2019
Cost: [17.64638758]
Epoch: 2020


Epoch: 2251
Cost: [16.04775356]
Epoch: 2252
Cost: [16.04233834]
Epoch: 2253
Cost: [16.03693387]
Epoch: 2254
Cost: [16.03154011]
Epoch: 2255
Cost: [16.02615705]
Epoch: 2256
Cost: [16.02078467]
Epoch: 2257
Cost: [16.01542293]
Epoch: 2258
Cost: [16.01007183]
Epoch: 2259
Cost: [16.00473134]
Epoch: 2260
Cost: [15.99940144]
Epoch: 2261
Cost: [15.99408211]
Epoch: 2262
Cost: [15.98877332]
Epoch: 2263
Cost: [15.98347506]
Epoch: 2264
Cost: [15.9781873]
Epoch: 2265
Cost: [15.97291002]
Epoch: 2266
Cost: [15.96764321]
Epoch: 2267
Cost: [15.96238683]
Epoch: 2268
Cost: [15.95714087]
Epoch: 2269
Cost: [15.95190531]
Epoch: 2270
Cost: [15.94668012]
Epoch: 2271
Cost: [15.94146529]
Epoch: 2272
Cost: [15.9362608]
Epoch: 2273
Cost: [15.93106662]
Epoch: 2274
Cost: [15.92588273]
Epoch: 2275
Cost: [15.92070911]
Epoch: 2276
Cost: [15.91554574]
Epoch: 2277
Cost: [15.91039261]
Epoch: 2278
Cost: [15.90524968]
Epoch: 2279
Cost: [15.90011694]
Epoch: 2280
Cost: [15.89499437]
Epoch: 2281
Cost: [15.88988195]
Epoch: 228

Cost: [14.40211283]
Epoch: 2715
Cost: [14.39993028]
Epoch: 2716
Cost: [14.39775195]
Epoch: 2717
Cost: [14.39557783]
Epoch: 2718
Cost: [14.39340791]
Epoch: 2719
Cost: [14.39124219]
Epoch: 2720
Cost: [14.38908065]
Epoch: 2721
Cost: [14.3869233]
Epoch: 2722
Cost: [14.38477011]
Epoch: 2723
Cost: [14.38262109]
Epoch: 2724
Cost: [14.38047622]
Epoch: 2725
Cost: [14.37833549]
Epoch: 2726
Cost: [14.3761989]
Epoch: 2727
Cost: [14.37406645]
Epoch: 2728
Cost: [14.37193811]
Epoch: 2729
Cost: [14.36981388]
Epoch: 2730
Cost: [14.36769375]
Epoch: 2731
Cost: [14.36557773]
Epoch: 2732
Cost: [14.36346578]
Epoch: 2733
Cost: [14.36135792]
Epoch: 2734
Cost: [14.35925413]
Epoch: 2735
Cost: [14.3571544]
Epoch: 2736
Cost: [14.35505873]
Epoch: 2737
Cost: [14.3529671]
Epoch: 2738
Cost: [14.35087951]
Epoch: 2739
Cost: [14.34879595]
Epoch: 2740
Cost: [14.34671642]
Epoch: 2741
Cost: [14.34464089]
Epoch: 2742
Cost: [14.34256938]
Epoch: 2743
Cost: [14.34050186]
Epoch: 2744
Cost: [14.33843833]
Epoch: 2745
Cost: [14.33

In [185]:
beta

array([[21.16356703],
       [ 6.6639869 ],
       [ 6.09808353]])